from pathlib import Path
path = Path('client/src/sections/Pricing.tsx')
text = path.read_text()
old = """        <div className=\"mt-4 rounded-[32px] border border-white/20 bg-gradient-to-br from-slate-900/80 to-indigo-900/60 p-8 shadow-[0_25px_60px_rgba(79,70,229,0.4)] backdrop-blur-3xl\">\n          <div className=\"flex flex-col gap-4 text-center md:flex-row md:items-center md:justify-between\">\n            <div>\n              <p className=\"text-xs uppercase tracking-[0.4em] text-indigo-300/70\">Guarantee</p>\n              <h3 className=\"font-display text-3xl font-bold text-white\">One-Time 21-Day Lead Guarantee</h3>\n              <p className=\"mt-2 text-sm text-white/70\">\n                You get 14 days free, then 7 paid days backed by our ?Book-1-or-Refund? promise. If Amunet doesn?t help\n                you book at least one new client in 21 days, you don?t pay. After that, normal monthly billing applies?\n                because by then, Amunet should already be earning her keep.\n              </p>\n            </div>\n            <div className=\"md:text-right\">\n              <a\n                className=\"mt-4 inline-flex items-center justify-center rounded-full bg-gradient-to-r from-indigo-500 to-purple-500 px-6 py-3 text-sm font-semibold uppercase tracking-wider text-white shadow-xl shadow-purple-900/60 transition hover:scale-105 md:mt-0\"\n                href=\"/dashboard\"\n              >\n                Start Free Trial\n              </a>\n              <p className=\"mt-2 text-xs text-white/60\">Start with risk-free lead capture in minutes.</p>\n            </div>\n          </div>\n        </div>\n"""
new = """        <div className=\"mt-4 rounded-[32px] border border-white/20 bg-gradient-to-br from-slate-900/80 to-indigo-900/60 p-8 shadow-[0_25px_60px_rgba(79,70,229,0.4)] backdrop-blur-3xl\">\n          <div className=\"flex flex-col gap-6 text-center md:flex-row md:items-center md:justify-between\">\n            <div className=\"md:text-left\">\n              <p className=\"text-xs uppercase tracking-[0.4em] text-indigo-300/70\">Guarantee</p>\n              <h3 className=\"font-display text-3xl font-bold text-white\">One-Time 21-Day Lead Guarantee</h3>\n              <p className=\"mt-2 text-sm text-white/70\">\n                You get 14 days free, then 7 paid days backed by our \"Book-1-or-Refund\" promise. If Amunet doesn\'t help\n                you book at least one new client in 21 days, you don\'t pay. After that, normal monthly billing applies-\n                because by then, Amunet should already be earning her keep.\n              </p>\n            </div>\n            <div className=\"flex flex-col items-center text-center space-y-2\">\n              <a\n                className=\"px-6 py-3 text-lg font-bold bg-indigo-600 text-white rounded-lg hover:bg-indigo-700\"\n                href=\"/dashboard\"\n              >\n                Start Free Trial\n              </a>\n              <p className=\"text-xs text-white/60\">Start with risk-free lead capture in minutes.</p>\n            </div>\n          </div>\n        </div>\n"""
if old not in text:
    raise SystemExit('old block not found')
text = text.replace(old, new)
path.write_text(text)
